name: Build (public/) and Deploy (Vite) to Firebase Hosting

on:
  push:
    branches:
      - release # change if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 24 and enable npm cache
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Show repo layout (debug)
        run: |
          echo "Repo root files:"
          ls -la
          echo "public/ files:"
          ls -la public || true

      - name: Install dependencies (in public/)
        working-directory: public
        run: |
          echo "Working directory: $(pwd)"
          if [ -f package-lock.json ]; then
            npm ci --prefer-offline --no-audit --progress=false || {
              echo "npm ci failed — falling back to npm install"
              npm install --prefer-offline --no-audit --progress=false
            }
          else
            npm install --prefer-offline --no-audit --progress=false
          fi

      - name: Build (Vite -> public/dist)
        working-directory: public
        run: npm run build
        env:
          CI: true
          # add any VITE_ secrets here if needed, e.g.:
          # VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Deploy to Firebase Hosting
        # action expects firebase.json at repo root; we set hosting.public to public/dist above
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: javascript-100
